testcontainers/moby-ryuk

main.go

This PR adds a timeout for `cli.Ping()` by using `context.WithTimeout()` to allow users to debug Testcontainer issues more easily.
I had a misconfigured `/etc/docker/daemon.json`, in which I included only `tcp://xxx` in `hosts` while omitting `unix:///var/run/docker.sock`. As a result, Ryuk is constantly stuck in `Ping()`, and Testcontainers fails with "Can not connect to Ryuk". Had there been a timeout and an error message, I might have found the problem earlier, without having to examine the Go source code.
I'm not an experienced Go programmer (started less than 24 hours ago because of this), so I'll be happy to know better ways of dealing with contexts.

Add timeout when pinging Docker daemon

---

main.go

https://github.com/testcontainers/testcontainers-node/issues/189

Prune all images, not just dangling images

---

.github/workflows/build-docker-image.yml

An apparent regression appeared in either buildkit/qemu which was causing the multi-arch build to fail.  #27 describes the problem. 
This PR pins the versions of these dependencies so that we should at least get reproduceable builds. When this PR was first created there was no working combination; however now it looks like this regression was fixed in some intermediate version of `tonistiigi/binfmt`.

Fix multi-arch build with pinned versions of buildx/QEMU images

---

main.go

This PR adds handling of the os signals SIGINT and SIGTERM so that the container will prune immediately after receiving one of them. Currently the process just stops and does not prune at all.

Prune on signals SIGINT and SIGTERM

---

.github/workflows/build-docker-image.yml
.github/workflows/release-drafter.yml

It uses `main` as branch name in the two GH workflows that used `master`
We are advocating from a neutral branch name, `main`.
- Closes #43
Rename the master branch to main using GH UI.

chore: use main as branch name in automation

---

.github/workflows/publish-docker-image.yml

It copies the current build pipeline to a push pipeline, removing any interaction to Docker Hub from the build one.
The push pipeline will remove any scripted conditional in the pipeline to detect that the Github event was triggered by a release. This is possible because the workflow will only listen for published releases events.
Separation of concerns: we want to build on pushes and PRs, but only publish on tags. It will also increase the maintainability of the pipelines: having separate descriptors will help reviewers to identify where a change must be done.
We could add snapshots to the push-to-main event. Because the tags will be stored at Docker Hub (no issue for us with the space), we could build&push the Docker image for the main branch, using the last commit as Docker tag. We …

chore(ci): only push Docker image on tags

---

.github/dependabot.yml

It adds dependabot config file, using a monthly schedule for updates
Keep dependencies up-to-date

chore: add dependabot updates

---

Dockerfile
main.go
main_test.go

- Workaround for https://github.com/testcontainers/testcontainers-go/issues/698
- Add generic label to the ryuk image `org.testcontainers.ryuk` which enables the ryuk to detect itself and prevent deletions.

Prevent Ryuk from removing itself

---

go.mod
go.sum

It bumps tc-go to the latest version
Do not wait for dependabot's next update, consuming the upstream of tc-go

chore: bump tc-go to v0.19.0

---

README.md
main.go
main_test.go

It supports configuring Ryuk to add verbosity when calling the Docker APIs. It can be set with the `RYUK_VERBOSE` environment variable, which accepts boolean values.
Everytime the Docker client is used to list/prune resources (containers, networks, volumes and images), a log will be produced if and only if the verbose variable is enabled.
Support debugging certain failures while accessing the Docker engine

chore: super simple verbose logs when pruning

---

main.go

The PR inverts the API version error check. It was `err != nil` before.
Yesterday, while tidying up after my tests, I accidentally inverted the error check. The fix is not considered for the latest API.
- Relates #75

fix: Invert the API version error check

---

README.md

Bump the Ryuk image tag in the README code snippet to `0.5.1`.
Better getting-started and debugging experience for users, that use the commands as provided in the README.

Update Ryuk tag in README to 0.5.1

---

.github/workflows/build-docker-image.yml
.github/workflows/golangci-lint.yml
.github/workflows/publish-docker-image.yml

:warning: This PR has been created with the [combine-prs](https://github.com/mdelapenya/gh-combine-prs) `gh` extension.
Command:/Users/mdelapenya/.local/share/gh/extensions/gh-combine-prs/gh-combine-prs --query author:app/dependabot --interactive --verbose --skip-pr-check.
It combines the following PRs:
- chore(deps): bump docker/setup-qemu-action from 2 to 3 (#107) @app/dependabot
- chore(deps): bump actions/setup-go from 3 to 5 (#106) @app/dependabot
- chore(deps): bump golangci/golangci-lint-action from 3.3.0 to 3.7.0 (#105) @app/dependabot
- Closes #107
- Closes #106
- Closes #105

chore(deps): bump docker/setup-qemu-action from 2 to 3, actions/setup-go from 3 to 5, golangci/golangci-lint-action from 3.3.0 to 3.7.0

---

.github/workflows/golangci-lint.yml

- chore: bump Go version in golangci workflow
- chore: bump golangci version

chore(deps): bump golangci-lint action and version from 1.50 to 1.55.2

---

.github/workflows/publish-docker-image.yml

This is a follow-up to #120 
- The manifest now contains entries with "unknown" architecture. The entries aren't relevant to our check on existence of expected "linux" and "windows" entries, so we're simply ignoring "unknown" architectures.
- The diff has been fixed to use our input from stdin instead of trying to read any files.

Fix the manifest check

---

.github/workflows/build-docker-image.yml

This is a follow-up for #130 to apply the same fix from the publish workflow to the build workflow.

Fix the manifest check for the build workflow

---

.github/workflows/publish-docker-image.yml

This PR is using the right job when releasing the Ryuk project.
It was possibly wrong after #120

fix(gh-actions): depend on the right workflow

---

.github/workflows/golangci-lint.yml
.golangci.yaml
reaper.go
reaper_test.go

Add a configuration file which makes it much more strict.
Fix shadowed error variables flagged by linter.
Remove CI timeout as its now present in the config.

ci: enhanced linting

---

README.md
reaper.go
reaper_test.go

It uses `Started` instead of `listening` in the log to define that Ryuk properly initialised.
To avoid breaking existing clients of Ryuk, which could be updating the Ryuk version in the properties file
- Relates https://github.com/testcontainers/testcontainers-java/issues/9369
I wonder what are the different use cases to have a different ryuk version at the properties level and not use the one provided by the library.
I acknowledge that we introduced a breaking change when we updated the log format to a more structured one, which we are fixing in this PR, but if the user puts a wrong version in the properties, like a very outdated ryuk version, what can we do in that case?

fix: use Started instead of listening

---

reaper.go
reaper_test.go

Fix shutdown after signal to allow the last client disconnect to trigger a prune check. Previous this would always wait for the shutdown timeout, which by default is 10 minutes, resulting in an unnecessarily slow shutdown.

fix: slow shutdown after signal

---

README.md
config.go
config_test.go
reaper.go
reaper_test.go
testdata/Dockerfile

Fix multiple filters which was only applying the removal of the last iterated set.
Add tests to validate that:
* Multiple filters are correctly processed
* Duplicate filters are correctly ignored
* Immediate shutdown occurs if no clients
This increasing code coverage to 89.4%.
Use best effort in removal if resource changes are detected after a shutdown has been signalled to allow as much to be cleaned up as possible.
This includes a new setting `ChangesRetryInterval` exposed by the env variable `RYUK_CHANGES_RETRY_INTERVAL` and defaults to 1 second which is used to control the interval between retries if resource changes are detected.

fix: multiple filters

---

windows/Dockerfile

Recent merges have failed the Windows build with this error:
> go: updating go.mod: open C:\app\go.mod: Access is denied.
After a quick research, we considered that it could be caused by the ContainerUser not having permissions to run that command. After verifying that the ContainerAdministrator user exists with administrative privileges (see https://hub.docker.com/layers/library/golang/1.23-nanoserver/images/sha256-0ee04e227947f7b6edd033eac8b48be8279aadb75ebc9fc8d36952e99eecaa9b), we are using that user to run the mod download.

fix: run mod download with ContainerAdministrator
